# conda version: 4.10.3, 4.11.0
name: nlp

channels:
  - pytorch

dependencies:
  - python=3.9
  - numpy=1.21.5
  - pandas=1.3.5
  - spacy=3.2.1
  - tensorflow=2.6.0
  - pytorch=1.10.1
  - cudatoolkit=11.3